import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { format, parseISO } from 'date-fns';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 10, fontFamily: 'Helvetica' },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 5 },
  subtitle: { fontSize: 12, color: '#666', marginBottom: 10 },
  table: {
    display: 'flex',
    width: '100%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#000',
  },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#000' },
  tableHeader: { backgroundColor: '#f0f0f0', fontWeight: 'bold' },
  tableCell: { padding: 5, flex: 1, borderRightWidth: 1, borderRightColor: '#000' },
  tableCellLast: { padding: 5, flex: 1 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, fontSize: 8, color: '#666' },
});

export interface Shift {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  employee: string;
  bureau: string;
  role: string;
}

export interface SchedulePDFProps {
  shifts: Shift[];
  startDate: string;
  endDate: string;
  bureau: string;
  generatedAt: string;
}

export function createSchedulePDF({
  shifts,
  startDate,
  endDate,
  bureau,
  generatedAt,
}: SchedulePDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>ShiftSmart Schedule</Text>
          <Text style={styles.subtitle}>
            {format(parseISO(startDate), 'MMM d, yyyy')} -{' '}
            {format(parseISO(endDate), 'MMM d, yyyy')}
            {bureau !== 'both' ? ` | ${bureau} Bureau` : ' | All Bureaus'}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={[styles.tableRow, styles.tableHeader]}>
            <Text style={styles.tableCell}>Date</Text>
            <Text style={styles.tableCell}>Time</Text>
            <Text style={styles.tableCell}>Employee</Text>
            <Text style={styles.tableCell}>Bureau</Text>
            <Text style={styles.tableCellLast}>Role</Text>
          </View>
          {shifts.map((shift) => (
            <View key={shift.id} style={styles.tableRow}>
              <Text style={styles.tableCell}>{format(parseISO(shift.date), 'MMM d')}</Text>
              <Text style={styles.tableCell}>
                {shift.startTime} - {shift.endTime}
              </Text>
              <Text style={styles.tableCell}>{shift.employee}</Text>
              <Text style={styles.tableCell}>{shift.bureau}</Text>
              <Text style={styles.tableCellLast}>{shift.role}</Text>
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text>Generated by ShiftSmart on {generatedAt} | Reuters Breaking News</Text>
        </View>
      </Page>
    </Document>
  );
}
